// Integration tests for the authentication flow: register, login, refresh,
// logout and /auth/me, exercised through the real HTTP app.
//
// The test env keeps the auth rate limit generous by default (see
// src/middlewares/rate-limit.ts): these tests do not set RATE_LIMIT_AUTH_MAX, so
// they run well below the limit and stay deterministic.
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { api } from './helpers/http.js';
import { cleanDatabase, disconnectDatabase, testPrisma } from './helpers/db.js';

const REFRESH_COOKIE_NAME = 'refreshToken';

const validRegister = () => ({
  name: 'Maria Silva',
  email: `maria-${crypto.randomUUID()}@example.test`,
  password: 'senha-super-secreta',
});

// Extracts the Set-Cookie header(s) as a raw string array.
const setCookieHeaders = (response: { headers: Record<string, unknown> }): string[] => {
  const raw = response.headers['set-cookie'];
  if (Array.isArray(raw)) return raw as string[];
  if (typeof raw === 'string') return [raw];
  return [];
};

// Finds the refresh cookie header generated by the app (name read from the
// real config contract, never hardcoded into the assertions).
const findRefreshCookie = (headers: string[]): string | undefined =>
  headers.find((cookie) => cookie.startsWith(`${REFRESH_COOKIE_NAME}=`));

// Registers a user through the real endpoint and returns the credentials used.
const registerUser = async (overrides: Partial<ReturnType<typeof validRegister>> = {}) => {
  const payload = { ...validRegister(), ...overrides };
  const response = await api().post('/auth/register').send(payload);
  return { payload, response };
};

// Logs in through the real endpoint, returning the response and the refresh
// cookie header (so callers can replay it as a cookie on later requests).
const loginUser = async (email: string, password: string) => {
  const response = await api().post('/auth/login').send({ email, password });
  const refreshCookie = findRefreshCookie(setCookieHeaders(response));
  return { response, refreshCookie };
};

describe('AUTH integration', () => {
  beforeAll(async () => {
    await cleanDatabase();
  });

  afterAll(async () => {
    await cleanDatabase();
    await disconnectDatabase();
  });

  // -------------------------------------------------------------------------
  // POST /auth/register
  // -------------------------------------------------------------------------
  describe('POST /auth/register', () => {
    it('cria o usuário com dados válidos, sem devolver passwordHash nem sessão', async () => {
      const { payload, response } = await registerUser();

      expect(response.status).toBe(201);
      expect(response.body).toEqual({
        user: {
          id: expect.any(String),
          name: payload.name,
          email: payload.email,
          createdAt: expect.any(String),
          updatedAt: expect.any(String),
        },
      });

      // O cadastro NÃO inicia sessão: sem access token e sem cookie de refresh.
      expect(response.body.accessToken).toBeUndefined();
      expect(setCookieHeaders(response)).toHaveLength(0);

      // Nunca expõe o hash da senha nem campos internos.
      expect(JSON.stringify(response.body)).not.toContain('passwordHash');
      expect(response.body.user.passwordHash).toBeUndefined();

      // O usuário foi realmente persistido, com a senha em hash (nunca em claro).
      const persisted = await testPrisma.user.findUnique({ where: { email: payload.email } });
      expect(persisted).not.toBeNull();
      expect(persisted?.name).toBe(payload.name);
      expect(persisted?.passwordHash).toBeTruthy();
      expect(persisted?.passwordHash).not.toBe(payload.password);
    });

    it('normaliza o email (trim + lowercase) ao cadastrar', async () => {
      const email = `mixed-${crypto.randomUUID()}@Example.Test`;
      const response = await api()
        .post('/auth/register')
        .send({
          name: 'Case Test',
          email: `  ${email}  `,
          password: 'senha-super-secreta',
        });

      expect(response.status).toBe(201);
      expect(response.body.user.email).toBe(email.toLowerCase());

      const persisted = await testPrisma.user.findUnique({
        where: { email: email.toLowerCase() },
      });
      expect(persisted).not.toBeNull();
    });

    it('rejeita email duplicado com 409 sem criar um segundo usuário', async () => {
      const { payload } = await registerUser();

      const before = await testPrisma.user.count({ where: { email: payload.email } });
      const response = await api().post('/auth/register').send({
        name: 'Outro Nome',
        email: payload.email,
        password: 'outra-senha-qualquer',
      });

      expect(response.status).toBe(409);
      expect(response.body.error.code).toBe('EMAIL_ALREADY_REGISTERED');
      // Não vaza detalhes internos do Prisma.
      expect(JSON.stringify(response.body)).not.toContain('P2002');
      expect(JSON.stringify(response.body)).not.toContain('prisma');

      const after = await testPrisma.user.count({ where: { email: payload.email } });
      expect(after).toBe(before);
      expect(after).toBe(1);
    });

    it('rejeita email inválido com 400 VALIDATION_ERROR', async () => {
      const response = await api().post('/auth/register').send({
        name: 'Sem Email',
        email: 'nao-e-email',
        password: 'senha-super-secreta',
      });

      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe('VALIDATION_ERROR');
      expect(response.body.error.issues).toEqual(
        expect.arrayContaining([expect.objectContaining({ path: 'email' })]),
      );
    });

    it('rejeita senha curta (mínimo 8) com 400', async () => {
      const response = await api()
        .post('/auth/register')
        .send({
          name: 'Senha Curta',
          email: `curta-${crypto.randomUUID()}@example.test`,
          password: '1234567',
        });

      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe('VALIDATION_ERROR');
      expect(response.body.error.issues).toEqual(
        expect.arrayContaining([expect.objectContaining({ path: 'password' })]),
      );
    });

    it('rejeita campos obrigatórios ausentes com 400', async () => {
      const response = await api()
        .post('/auth/register')
        .send({
          email: `sem-nome-${crypto.randomUUID()}@example.test`,
          password: 'senha-super-secreta',
        });

      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe('VALIDATION_ERROR');
    });

    it('ignora campos extras sem mass assignment (não os persiste)', async () => {
      const email = `extras-${crypto.randomUUID()}@example.test`;
      const response = await api().post('/auth/register').send({
        name: 'Com Extras',
        email,
        password: 'senha-super-secreta',
        id: 'id-forjado',
        passwordHash: 'hash-forjado',
        createdAt: '2000-01-01T00:00:00.000Z',
      });

      // O schema atual NÃO é estrito: campos desconhecidos são removidos (strip),
      // então o cadastro é aceito, mas os extras não têm efeito.
      expect(response.status).toBe(201);

      const persisted = await testPrisma.user.findUnique({ where: { email } });
      expect(persisted).not.toBeNull();
      expect(persisted?.id).not.toBe('id-forjado');
      expect(persisted?.passwordHash).not.toBe('hash-forjado');
    });
  });

  // -------------------------------------------------------------------------
  // POST /auth/login
  // -------------------------------------------------------------------------
  describe('POST /auth/login', () => {
    it('autentica com credenciais válidas e emite access token + cookie de refresh', async () => {
      const { payload } = await registerUser({
        name: 'Login Válido',
        password: 'minha-senha-valida',
      });

      const { response, refreshCookie } = await loginUser(payload.email, payload.password);

      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        user: {
          id: expect.any(String),
          name: payload.name,
          email: payload.email,
          createdAt: expect.any(String),
          updatedAt: expect.any(String),
        },
        accessToken: expect.any(String),
      });

      // Sem hash de senha na resposta.
      expect(JSON.stringify(response.body)).not.toContain('passwordHash');

      // Cookie de refresh presente, HttpOnly e restrito a /auth.
      expect(refreshCookie).toBeDefined();
      expect(refreshCookie?.toLowerCase()).toContain('httponly');
      expect(refreshCookie).toContain('Path=/auth');

      // O access token emitido autentica em /auth/me.
      const me = await api()
        .get('/auth/me')
        .set('Authorization', `Bearer ${response.body.accessToken}`);
      expect(me.status).toBe(200);
      expect(me.body.user.id).toBe(response.body.user.id);
    });

    it('rejeita senha incorreta com 401 INVALID_CREDENTIALS e sem token', async () => {
      const { payload } = await registerUser({ password: 'senha-correta-123' });

      const response = await api()
        .post('/auth/login')
        .send({ email: payload.email, password: 'senha-errada-456' });

      expect(response.status).toBe(401);
      expect(response.body.error.code).toBe('INVALID_CREDENTIALS');
      expect(response.body.accessToken).toBeUndefined();
      expect(setCookieHeaders(response)).toHaveLength(0);
    });

    it('rejeita usuário inexistente com a MESMA resposta de senha incorreta (anti-enumeração)', async () => {
      const response = await api()
        .post('/auth/login')
        .send({
          email: `inexistente-${crypto.randomUUID()}@example.test`,
          password: 'qualquer-senha',
        });

      expect(response.status).toBe(401);
      expect(response.body).toEqual({
        error: { message: 'Invalid email or password', code: 'INVALID_CREDENTIALS' },
      });
      expect(response.body.error.message).not.toMatch(/not found|não encontrado|does not exist/i);
    });

    it('rejeita payload inválido com 400 (email e senha ausentes)', async () => {
      const response = await api().post('/auth/login').send({});

      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe('VALIDATION_ERROR');
    });

    it('ignora campos extras no login (sem efeito)', async () => {
      const { payload } = await registerUser({ password: 'senha-extra-larga' });

      const response = await api().post('/auth/login').send({
        email: payload.email,
        password: payload.password,
        userId: crypto.randomUUID(),
        role: 'admin',
      });

      expect(response.status).toBe(200);
      expect(response.body.user.id).toEqual(expect.any(String));
      expect(response.body.user.role).toBeUndefined();
    });
  });

  // -------------------------------------------------------------------------
  // POST /auth/refresh
  // -------------------------------------------------------------------------
  describe('POST /auth/refresh', () => {
    it('emite um novo access token a partir de um refresh cookie válido', async () => {
      const { payload } = await registerUser({ password: 'senha-refresh-1' });
      const { response: loginResponse, refreshCookie } = await loginUser(
        payload.email,
        payload.password,
      );
      expect(refreshCookie).toBeDefined();

      const refresh = await api()
        .post('/auth/refresh')
        .set('Cookie', refreshCookie as string);

      expect(refresh.status).toBe(200);
      expect(refresh.body).toEqual({ accessToken: expect.any(String) });

      // O novo access token autentica em /auth/me para o MESMO usuário.
      const me = await api()
        .get('/auth/me')
        .set('Authorization', `Bearer ${refresh.body.accessToken}`);
      expect(me.status).toBe(200);
      expect(me.body.user.id).toBe(loginResponse.body.user.id);
    });

    it('retorna 401 REFRESH_TOKEN_REQUIRED sem cookie e não cria sessão', async () => {
      const response = await api().post('/auth/refresh');

      expect(response.status).toBe(401);
      expect(response.body).toEqual({
        error: { message: 'Refresh token is required', code: 'REFRESH_TOKEN_REQUIRED' },
      });
      expect(response.body.accessToken).toBeUndefined();
    });

    it('retorna 401 INVALID_REFRESH_TOKEN para cookie adulterado', async () => {
      const response = await api()
        .post('/auth/refresh')
        .set('Cookie', `${REFRESH_COOKIE_NAME}=not-a-real-token`);

      expect(response.status).toBe(401);
      expect(response.body.error.code).toBe('INVALID_REFRESH_TOKEN');
      expect(response.body.accessToken).toBeUndefined();
    });

    it('retorna 401 para um refresh token assinado com outro segredo (forjado)', async () => {
      // Token estruturalmente válido (JWT), porém com assinatura inválida.
      const forged = [
        Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'),
        Buffer.from(JSON.stringify({ userId: crypto.randomUUID() })).toString('base64url'),
        'assinatura-invalida',
      ].join('.');

      const response = await api()
        .post('/auth/refresh')
        .set('Cookie', `${REFRESH_COOKIE_NAME}=${forged}`);

      expect(response.status).toBe(401);
      expect(response.body.error.code).toBe('INVALID_REFRESH_TOKEN');
    });
  });

  // -------------------------------------------------------------------------
  // GET /auth/me
  // -------------------------------------------------------------------------
  describe('GET /auth/me', () => {
    it('retorna os dados públicos do usuário autenticado (token do login real)', async () => {
      const { payload } = await registerUser({ name: 'Me Test', password: 'senha-me-123' });
      const { response: loginResponse } = await loginUser(payload.email, payload.password);

      const response = await api()
        .get('/auth/me')
        .set('Authorization', `Bearer ${loginResponse.body.accessToken}`);

      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        user: {
          id: expect.any(String),
          name: 'Me Test',
          email: payload.email,
          createdAt: expect.any(String),
          updatedAt: expect.any(String),
        },
      });
      expect(JSON.stringify(response.body)).not.toContain('passwordHash');
      expect(response.body.user.passwordHash).toBeUndefined();
    });

    it('retorna 401 AUTH_REQUIRED sem autenticação', async () => {
      const response = await api().get('/auth/me');

      expect(response.status).toBe(401);
      expect(response.body).toEqual({
        error: { message: 'Authentication required', code: 'AUTH_REQUIRED' },
      });
    });

    it('retorna 401 INVALID_ACCESS_TOKEN para token inválido', async () => {
      const response = await api().get('/auth/me').set('Authorization', 'Bearer token-invalido');

      expect(response.status).toBe(401);
      expect(response.body.error.code).toBe('INVALID_ACCESS_TOKEN');
    });
  });

  // -------------------------------------------------------------------------
  // POST /auth/logout
  // -------------------------------------------------------------------------
  describe('POST /auth/logout', () => {
    it('limpa o cookie de refresh e responde 204', async () => {
      const { payload } = await registerUser({ password: 'senha-logout-1' });
      const { refreshCookie } = await loginUser(payload.email, payload.password);
      expect(refreshCookie).toBeDefined();

      const response = await api()
        .post('/auth/logout')
        .set('Cookie', refreshCookie as string);

      expect(response.status).toBe(204);

      // O cookie é invalidado via Set-Cookie com expiração no passado/vazio.
      const cookies = setCookieHeaders(response);
      const cleared = findRefreshCookie(cookies);
      expect(cleared).toBeDefined();
      expect(cleared?.toLowerCase()).toMatch(/expires=thu, 01 jan 1970|max-age=0/);
    });

    it('responde 204 mesmo sem autenticação (contrato atual: logout é idempotente)', async () => {
      const response = await api().post('/auth/logout');

      expect(response.status).toBe(204);
    });
  });
});
